apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www-nginx
  template:
    metadata:
      labels:
        app: www-nginx
    spec:
      volumes:
        - name: website-content
          emptyDir: {}

      initContainers:
        - name: init-symlink
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /tmp/git/repo
              ln -s /tmp/git/repo /tmp/git/html
          volumeMounts:
            - name: website-content
              mountPath: /tmp/git

      containers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.4.0
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/lee89tw14/switching-harmony.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_WAIT
              value: "30"
            - name: GIT_SYNC_ROOT
              value: "/tmp/git"
            - name: GIT_SYNC_DEST
              value: "repo"

            # Basic認証情報
            - name: GITSYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-sync-credentials
                  key: username

            - name: GITSYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-sync-credentials
                  key: password

          volumeMounts:
            - name: website-content
              mountPath: /tmp/git

        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /usr/share/nginx/html
              subPath: "html"
