apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www-nginx
  template:
    metadata:
      labels:
        app: www-nginx
    spec:
      volumes:
        - name: website-content
          emptyDir: {}

      containers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.4.0
          env:
            # 1) クローン元のGitリポジトリ
            - name: GIT_SYNC_REPO
              value: "https://github.com/lee89tw14/switching-harmony.git"

            # 2) ブランチ
            - name: GIT_SYNC_BRANCH
              value: "main"

            # 3) 何秒ごとにpullするか
            - name: GIT_SYNC_WAIT
              value: "30"

            # 4) クローン先のルートディレクトリ (Nginxのhtmlディレクトリにそのまま書き込む)
            - name: GIT_SYNC_ROOT
              value: "/usr/share/nginx/html"

            # 5) DESTを空文字("")にすることで、GIT_SYNC_ROOT 直下にクローン
            - name: GIT_SYNC_DEST
              value: ""

            # 6) プライベートリポジトリの場合に必要な認証情報 (ここではSecret参照)
            - name: GIT_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-sync-credentials
                  key: username
            - name: GIT_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-sync-credentials
                  key: password

          # git-sync と Nginx が同じ emptyDir ボリュームを共有
          volumeMounts:
            - name: website-content
              mountPath: /usr/share/nginx/html

        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content
              mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: www-nginx
spec:
  type: LoadBalancer       
  selector:
    app: www-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  
