apiVersion: v1
kind: Service
metadata:
  name: my-website-service
spec:
  type: LoadBalancer       
  selector:
    app: www-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  
