apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-java
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: ""
  storageClassName: "truenas-nfs-csi"
  resources:
    requests:
      storage: 5Gi
        #volumeName: nfs-pv-java