apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-grafana
spec:
  storageClassName: truenas-nfs-csi
  volumeName: test-pvc-jellyfin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

